#!/bin/bash
# Setup script for GCP Cloud Shell environment
#
# This script:
# 1. Installs required dependencies
# 2. Configures gcloud authentication
# 3. Sets up environment variables
# 4. Validates the setup
#
# Usage:
#   ./scripts/setup_gcp.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

cd "$PROJECT_ROOT"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${GREEN}🔧 GCP Cloud Shell Setup for GUI Agent${NC}"
echo "========================================"

# Check Python version
echo -e "\n${BLUE}Checking Python version...${NC}"
python_version=$(python3 --version 2>&1 | cut -d' ' -f2)
echo "Python version: $python_version"

major=$(echo "$python_version" | cut -d'.' -f1)
minor=$(echo "$python_version" | cut -d'.' -f2)

if [ "$major" -lt 3 ] || ([ "$major" -eq 3 ] && [ "$minor" -lt 11 ]); then
    echo -e "${RED}Error: Python 3.11+ is required${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Python version OK${NC}"

# Install dependencies
echo -e "\n${BLUE}Installing Python dependencies...${NC}"
pip install -e ".[dev,mock-server]" --quiet

echo -e "${GREEN}✓ Dependencies installed${NC}"

# Setup gcloud authentication
echo -e "\n${BLUE}Checking gcloud authentication...${NC}"

if ! gcloud auth list --filter=status:ACTIVE --format="value(account)" | head -1 | grep -q "@"; then
    echo -e "${YELLOW}No active gcloud authentication found.${NC}"
    echo "Running 'gcloud auth application-default login'..."
    gcloud auth application-default login
fi

current_account=$(gcloud auth list --filter=status:ACTIVE --format="value(account)" | head -1)
echo -e "${GREEN}✓ Authenticated as: $current_account${NC}"

# Get project info
echo -e "\n${BLUE}Checking GCP project...${NC}"
current_project=$(gcloud config get-value project 2>/dev/null)

if [ -z "$current_project" ]; then
    echo -e "${YELLOW}No default project set.${NC}"
    echo "Available projects:"
    gcloud projects list --format="value(projectId)" | head -5
    echo ""
    read -p "Enter project ID: " current_project
    gcloud config set project "$current_project"
fi

echo -e "${GREEN}✓ Using project: $current_project${NC}"

# Check Vertex AI API
echo -e "\n${BLUE}Checking Vertex AI API...${NC}"
if gcloud services list --enabled --filter="name:aiplatform.googleapis.com" --format="value(name)" | grep -q "aiplatform"; then
    echo -e "${GREEN}✓ Vertex AI API is enabled${NC}"
else
    echo -e "${YELLOW}Vertex AI API not enabled. Enabling now...${NC}"
    gcloud services enable aiplatform.googleapis.com
    echo -e "${GREEN}✓ Vertex AI API enabled${NC}"
fi

# Create/update .env file
echo -e "\n${BLUE}Configuring environment...${NC}"

if [ ! -f .env ]; then
    cp .env.example .env
fi

# Update .env with GCP settings
cat > .env << EOF
# Auto-generated by setup_gcp.sh
# GCP Cloud Shell Configuration

# Vertex AI Authentication (using gcloud)
GOOGLE_GENAI_USE_VERTEXAI=TRUE
GOOGLE_CLOUD_PROJECT=$current_project
GOOGLE_CLOUD_LOCATION=us-central1

# Model Configuration
MODEL_NAME=gemini-2.5-flash

# Playwright MCP Server (run separately)
PLAYWRIGHT_MCP_URL=http://localhost:3000/sse
BROWSER_HEADLESS=true

# Observability
PHOENIX_HOST=localhost
PHOENIX_PORT=6006
PHOENIX_COLLECTOR_ENDPOINT=http://localhost:6006/v1/traces
ENABLE_TRACING=true

# Agent Configuration
MAX_AGENT_STEPS=20
BROWSER_TIMEOUT=30

# Mock Server
MOCK_SERVER_HOST=localhost
MOCK_SERVER_PORT=8080
EOF

echo -e "${GREEN}✓ Environment configured${NC}"

# Summary
echo -e "\n${GREEN}========================================${NC}"
echo -e "${GREEN}✅ Setup Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "Configuration:"
echo "  Project: $current_project"
echo "  Region: us-central1"
echo "  Model: gemini-2.5-flash"
echo ""
echo "Next steps:"
echo "  1. Start Playwright MCP server:"
echo "     npx @anthropic-ai/mcp-server-playwright --port 3000"
echo ""
echo "  2. (Optional) Start Phoenix for tracing:"
echo "     docker compose up -d phoenix"
echo ""
echo "  3. Run the agent:"
echo "     ./scripts/run_headless.sh"
echo ""
echo "  4. Or run tests:"
echo "     make test-fast"
